name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Frontend build steps
    - name: Use Node.js 23.x
      uses: actions/setup-node@v4
      with:
        node-version: 23.x
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: Setup npm
      working-directory: frontend
      run: npm ci
    - name: Build the frontend
      working-directory: frontend
      run: npm run build
      env:
        VUE_APP_BASE_URL: origin_slash_api
    # Docker build step
    - name: Build the Docker image
      run: |
        docker build . --file docker/Dockerfile --tag pax-avize:latest
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push the Docker image
      run: |
        docker tag pax-avize:latest ${{ secrets.DOCKER_USERNAME }}/pax-avize:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/pax-avize:latest
  build-electron-app:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 23.x

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          # release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          package_root: frontend
          use_vue_cli: true
          args:
            "--win"
