name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Frontend build steps
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: Setup npm
      working-directory: frontend
      run: npm ci
    - name: Build the frontend
      working-directory: frontend
      run: npm run build
      env:
        VUE_APP_BASE_URL: origin_slash_api
    # Docker build step
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag ianosd/pax-avize:$(date +%s)
